CREATE TABLE `saravana_embassy_home_banner` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `created_date_time` datetime NOT NULL,
  `updated_date_time` datetime NOT NULL,
 `creator` mediumtext NOT NULL,
 `creator_name` mediumtext NOT NULL,
 `position_name` mediumtext NOT NULL,
 `banner_image` mediumtext NOT NULL,
 `banner_position` mediumtext NOT NULL,
 `banner_category_id` mediumtext NOT NULL,
 `deleted` int(11) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `saravana_embassy_meta_tags` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `created_date_time` datetime NOT NULL,
 `updated_date_time` datetime NOT NULL,
 `creator` mediumtext NOT NULL,
 `creator_name` mediumtext NOT NULL,
 `meta_file_name` mediumtext NOT NULL,
 `meta_title` mediumtext NOT NULL,
 `meta_keywords` mediumtext NOT NULL,
 `meta_description` mediumtext NOT NULL,
 `deleted` int(11) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `saravana_embassy_estimate` (
 `id` int(100) NOT NULL AUTO_INCREMENT,
 `created_date_time` datetime NOT NULL,
 `updated_date_time` datetime NOT NULL,
 `creator` mediumtext NOT NULL,
 `creator_name` mediumtext NOT NULL,
 `bill_company_id` mediumtext NOT NULL,
 `bill_company_name` mediumtext NOT NULL,
 `bill_company_details` mediumtext NOT NULL,
 `estimate_id` mediumtext NOT NULL,
 `estimate_number` mediumtext NOT NULL,
 `estimate_date` date NOT NULL,
 `customer_id` mediumtext NOT NULL,
 `customer_name` mediumtext NOT NULL,
 `customer_district` mediumtext NOT NULL,
 `customer_name_mobile_city` mediumtext NOT NULL,
 `customer_details` mediumtext NOT NULL,
 `estimate_type` mediumtext NOT NULL,
 `gst_option` mediumtext NOT NULL,
 `tax_option` mediumtext NOT NULL,
 `product_id` mediumtext NOT NULL,
 `product_name` mediumtext NOT NULL,
 `attribute_id` mediumtext NOT NULL,
 `attribute_name` mediumtext NOT NULL,
 `attribute_value_id` mediumtext NOT NULL,
 `attribute_value_name` mediumtext NOT NULL,
 `product_quantity` mediumtext NOT NULL,
 `product_price` mediumtext NOT NULL,
 `final_price` mediumtext NOT NULL,
 `product_tax` mediumtext NOT NULL,
 `product_amount` mediumtext NOT NULL,
 `sub_total` mediumtext NOT NULL,
 `discount` mediumtext NOT NULL,
 `discount_name` mediumtext NOT NULL,
 `discount_value` mediumtext NOT NULL,
 `discounted_total` mediumtext NOT NULL,
 `extra_charges` mediumtext NOT NULL,
 `extra_charges_name` mediumtext NOT NULL,
 `extra_charges_value` mediumtext NOT NULL,
 `extra_charges_total` mediumtext NOT NULL,
 `extra_charges_tax` mediumtext NOT NULL,
 `company_state` mediumtext NOT NULL,
 `party_state` mediumtext NOT NULL,
 `taxable_value` mediumtext NOT NULL,
 `cgst_value` mediumtext NOT NULL,
 `sgst_value` mediumtext NOT NULL,
 `igst_value` mediumtext NOT NULL,
 `total_tax_value` mediumtext NOT NULL,
 `total_amount` mediumtext NOT NULL,
 `round_off` mediumtext NOT NULL,
 `bill_total` mediumtext NOT NULL,
 `total_quantity` mediumtext NOT NULL,
 `is_invoiced` int(100) NOT NULL,
 `invoice_id` mediumtext NOT NULL,
 `invoice_number` mediumtext NOT NULL,
 `cancelled` int(100) NOT NULL,
 `deleted` int(100) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
